import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Lufga_Bold from "next/font/local";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});
const lufga = Lufga_Bold({
  variable: "--font-lufga",
  src: "../fonts/LufgaBold.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lufga.variable} ${workSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
